### ISSUE TITLE
Publish already builded version on NPM

### ISSUE THREAD

**Issue by Kerumen** [tkqubo/conditional-decorator#6]
`npm install conditional-decorator` failed with the following error:

```
> conditional-decorator@0.1.4 install /Users/yann/git/commander/node_modules/conditional-decorator
> tsd --config tsd.json reinstall --overwrite

sh: tsd: command not found
```

It's because I didn't have `tsd`. Installing it globally solved the problem.

The library should publish already builded version to npm though.

**Comment by tkqubo** [comment]
Oh sorry I was stupid.  I'll fix this...

In this case keeping `dist` directory in the repo is OK?

**Comment by tkqubo** [comment]
I believe `0.1.7` can be installed.  I would appreciate it if you could check it.  Anyway sorry for my late response @Kerumen

**Comment by Kerumen** [comment]
@tkqubo It's ok now! Thanks :)
